# Generated by Django 3.2.16 on 2022-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_theme', models.CharField(max_length=256)),
                ('question_chapter', models.CharField(max_length=256)),
                ('question_text', models.TextField()),
                ('question_response1', models.TextField()),
                ('question_response2', models.TextField()),
                ('question_response3', models.TextField()),
                ('question_response4', models.TextField()),
                ('question_valid', models.IntegerField()),
            ],
        ),
    ]
