# Generated by Django 3.2.16 on 2022-12-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registration_data',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='registration_data_end',
            new_name='registration_date_end',
        ),
    ]
