# Generated by Django 3.2.16 on 2022-12-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_course_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
