# Generated by Django 3.2.16 on 2022-12-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_registration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date_end',
            field=models.DateTimeField(null=True),
        ),
    ]
