# Generated by Django 3.2.16 on 2022-12-17 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0009_questionpack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionPack',
            new_name='QuizIntent',
        ),
        migrations.RenameField(
            model_name='quizintent',
            old_name='questionpack_intent',
            new_name='quizintent_intent',
        ),
        migrations.RenameField(
            model_name='quizintent',
            old_name='questionpack_user',
            new_name='quizintent_user',
        ),
    ]
