# Generated by Django 3.2.16 on 2022-12-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20221217_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizintent',
            name='quizintent_active',
            field=models.IntegerField(null=True),
        ),
    ]
