# Generated by Django 3.2.16 on 2022-12-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_quizintent_quizintent_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizintent',
            name='quizintent_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.course'),
        ),
    ]
