# Generated by Django 3.2.16 on 2022-12-20 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_quizintent_quizintent_dateinit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfinalized',
            name='quizfinalized_dateEnd',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizfinalized',
            name='quizfinalized_dateInit',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
