# Generated by Django 3.2.16 on 2022-12-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20221220_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_explanation',
            field=models.TextField(null=True),
        ),
    ]
