# Generated by Django 3.2.16 on 2023-01-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_alter_quizfinalized_quizfinalized_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.course'),
        ),
    ]
